server:
  port: ${SERVER_PORT:5000}

---

spring:
  application:
    name: catalog-service
  zipkin:
    base-url: http://127.0.0.1:9411/
  main:
    allow-bean-definition-overriding: true
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost:8761}/eureka/
    registerWithEureka: true
    enabled: true
  instant:
    hostname: localhost

spring-doc:
  api-docs:
    path: /api-docs
    swagger-ui:
      operationsSorter: method

---

spring:
  batch:
    jdbc:
      initialize-schema: always

---

Spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/msu_book_store?autoReconnect=true&useSSL=false
    username: root
    password: Pass$123_@2023
    initialize: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    use_sql_comments: true
    format_sql: true


