server:
  port: ${SERVER_PORT:9000}

---

spring:
  application:
    name: feign-service
  zipkin:
    base-url: http://127.0.0.1:9411/
  main:
    allow-bean-definition-overriding: true
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost:8761}/eureka/
    registerWithEureka: true
    enabled: true
  instant:
    hostname: localhost

spring-doc:
  api-docs:
    path: /api-docs
    swagger-ui:
      operationsSorter: method

---




